# render.yaml

services:
  - type: web
    name: auction-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:sqlserver://auction-database:1433;encrypt=true;trustServerCertificate=true;databaseName=DB_AUCTION;"
      - key: SPRING_DATASOURCE_USERNAME
        value: "sa"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "Thanhth@nh1"

  - type: web
    name: auction-database
    runtime: docker
    dockerfilePath: ./db/Dockerfile
    envVars:
      - key: SA_PASSWORD
        value: "Thanhth@nh1"
      - key: ACCEPT_EULA
        value: "Y"
    healthCheckPath: /

    # Ensuring init.sql is executed
    startCommand: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -d master -i /usr/src/app/init.sql"
